package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class CreateContactTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @BeforeTest
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "D:\\Autotests\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    login("admin", "secret");
  }

  private void login(String username, String password) {
    driver.get("http://localhost/addressbook/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("user")).sendKeys(username);
    driver.findElement(By.name("pass")).sendKeys(password);
    driver.findElement(By.name("pass")).sendKeys(Keys.ENTER);
  }

  @AfterTest
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testCreateContact() {
    initContactCreation();
    fillContactForm(new ContactData("Test", "Test", "Test", "Testing", "Samara", "88005553535", "marino4ka163@mail.ru", "1997", "//option[. = '28']", "//option[. = 'January']"));
    submitContactCreation();
  }

  private void submitContactCreation() {
    driver.findElement(By.linkText("home")).click();
  }

  private void fillContactForm(ContactData contactData) {
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys(contactData.getFirstname());
    driver.findElement(By.name("middlename")).click();
    driver.findElement(By.name("middlename")).sendKeys(contactData.getMiddlename());
    driver.findElement(By.name("lastname")).sendKeys(contactData.getLastname());
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys(contactData.getNickname());
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys(contactData.getAddress());
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.cssSelector("label:nth-child(30)")).click();
    driver.findElement(By.name("mobile")).click();
    driver.findElement(By.name("mobile")).sendKeys(contactData.getMobile());
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys(contactData.getEmail());
    driver.findElement(By.name("theform")).click();
    changeBday(contactData.getByear(), contactData.getBday(), contactData.getBmonth());
    driver.findElement(By.name("theform")).click();
    changeGroup();
    driver.findElement(By.name("new_group")).click();
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.cssSelector("input:nth-child(87)")).click();
  }

  private void changeGroup() {
    driver.findElement(By.name("new_group")).click();
    {
      WebElement dropdown = driver.findElement(By.name("new_group"));
      dropdown.findElement(By.xpath("//option[. = 'group1']")).click();
    }
  }

  private void changeBday(String byear, String bday, String bmonth) {
    driver.findElement(By.name("bday")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bday"));
      dropdown.findElement(By.xpath(bday)).click();
    }
    driver.findElement(By.name("bday")).click();
    driver.findElement(By.name("bmonth")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bmonth"));
      dropdown.findElement(By.xpath(bmonth)).click();
    }
    driver.findElement(By.name("bmonth")).click();
    driver.findElement(By.name("byear")).click();
    driver.findElement(By.name("byear")).sendKeys(byear);
  }

  private void initContactCreation() {
    driver.findElement(By.linkText("add new")).click();
  }
}
