package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class CreateContactTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @BeforeTest
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "D:\\Autotests\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @AfterTest
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createContact() {
    driver.get("http://localhost/addressbook/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("user")).sendKeys("admin");
    driver.findElement(By.name("pass")).sendKeys("secret");
    driver.findElement(By.name("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("add new")).click();
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys("Test");
    driver.findElement(By.name("middlename")).click();
    driver.findElement(By.name("middlename")).sendKeys("Test");
    driver.findElement(By.name("lastname")).sendKeys("Test");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("Testing");
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys("Samara");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.cssSelector("label:nth-child(30)")).click();
    driver.findElement(By.name("mobile")).click();
    driver.findElement(By.name("mobile")).sendKeys("88005553535");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("marino4ka163@mail.ru");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("bday")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bday"));
      dropdown.findElement(By.xpath("//option[. = '28']")).click();
    }
    driver.findElement(By.name("bday")).click();
    driver.findElement(By.name("bmonth")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bmonth"));
      dropdown.findElement(By.xpath("//option[. = 'January']")).click();
    }
    driver.findElement(By.name("bmonth")).click();
    driver.findElement(By.name("byear")).click();
    driver.findElement(By.name("byear")).sendKeys("1997");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("new_group")).click();
    {
      WebElement dropdown = driver.findElement(By.name("new_group"));
      dropdown.findElement(By.xpath("//option[. = 'group1']")).click();
    }
    driver.findElement(By.name("new_group")).click();
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.cssSelector("input:nth-child(87)")).click();
    driver.findElement(By.linkText("home")).click();
  }
}
