package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;

public class TestCreateGroupTest {
  private WebDriver driver;
  JavascriptExecutor js;

  @BeforeTest
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "D:\\Autotests\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    Map<String, Object> vars = new HashMap<String, Object>();
    driver.get("http://localhost/addressbook/group.php");
    driver.manage().window().setSize(new Dimension(778, 425));
    driver.findElement(By.name("user")).sendKeys("admin");
    driver.findElement(By.name("pass")).sendKeys("secret");
    driver.findElement(By.name("pass")).sendKeys(Keys.ENTER);
  }
  @AfterTest
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testCreateGroup() {
    driver.findElement(By.name("new")).click();
    driver.findElement(By.name("group_name")).click();
    driver.findElement(By.name("group_name")).sendKeys("group1");
    driver.findElement(By.name("group_header")).sendKeys("group2");
    driver.findElement(By.name("group_footer")).sendKeys("group3");
    driver.findElement(By.name("submit")).click();
    driver.findElement(By.linkText("groups")).click();
  }
}
