package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.model.GroupData;

import java.util.List;

public class GroupDeletionTests extends TestBase {

    @BeforeMethod
    public void ensurePreconditions(){
        app.goTo().groupPage();
        if (app.group().list().size() == 0) { //наличие группы
            app.group().create(new GroupData("test1", null, null));//создание группы
        }
    }

    @Test
    public void testGroupDeletion() {
        List<GroupData> before = app.group().list();
        //int before = app.getGroupHelper().getGroupCount();
        int index = before.size() - 1;
        app.group().delete(index);
        List<GroupData> after = app.group().list();
        Assert.assertEquals(after.size(), before.size() - 1);

        before.remove(index);//лишний элемент удаляем из списка before
        Assert.assertEquals(before, after);
    }
}
